// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chlltfkztqvcvsfmjnbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNobGx0Zmt6dHF2Y3ZzZm1qbmJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwOTQyMDcsImV4cCI6MjA3NDY3MDIwN30.2gnBqRcUihWynaorsxEVTVQo1g7EWUKdsq1aDcZCVNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});